# Site settings
title: "Yuri Banens Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Yuri Banens"
resume_title:                   "Libraries, Law, Ballroom & Boxing"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "spamyuri@me.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "0401-945-145"
resume_contact_address:         "6 Bernini Drive, Coombabah"

resume_header_contact_info:     "6 Bernini Drive, Coombabah • 0401-945-145 • iamagreattrainer@me.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Experienced and knowledgeable educator of both youth and adults. Graduate teacher, facilitator and mentor. Wide industry and project experience. Extensive media and technical knowledge.  Law student. Ballroom dancer.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ybanens"
  resume_twitter_url:           "http://twitter.com/ybanens"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/yuribanens"
  resume_instagram_url:         "https://www.instagram.com/ybanens"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
